title: Greek Evaluation
description: >
  Evaluation workflows for Ancient Greek language pipelines.

directories: ["assets", "corpus", "scripts", "predictions", "metrics"]

commands:
  - name: install
    script:
      - "bash scripts/create_environments.sh"
  - name: fetch_assets
    help: Fetches treebank data in spaCy binary and coNLL.
    script:
      - "bash scripts/fetch_treebanks.sh"
  - name: preprocess
    help: Preprocesses fetched assets
    script:
      - "bash scripts/prepare_treebanks.sh"
  - name: evaluate_cltk
    help: Evaluates CLTK
    script:
      - "bash scripts/evaluate_cltk.sh"
  - name: evaluate_stanza
  # DO stuff