title: Greek Evaluation
description: >
  Evaluation workflows for Ancient Greek language pipelines.

directories: ["assets", "corpus", "scripts", "predictions", "models", "metrics"]

commands:
  - name: install
    script:
      - "bash scripts/serverside_deps.sh"
      - "bash scripts/create_environments.sh"

  - name: fetch_assets
    help: Fetches treebank data in spaCy binary and coNLL.
    script:
      - "bash scripts/fetch_treebanks.sh"

  - name: preprocess
    help: Preprocesses fetched assets
    script:
      - "bash scripts/prepare_treebanks.sh"

  - name: evaluate_cltk
    help: Evaluates CLTK
    script:
      - "bash scripts/cltk/evaluate_cltk.sh"

  - name: evaluate_stanza
    help: Get stanza models, run them on test folds, generate repot
    script:
      - "bash scripts/stanza/evaluate_stanza.sh"

  - name: evaluate_udpipe
    help: Get udpipe models, run them on test folds, generate report
    script:
      - "bash scripts/udpipe/evaluate_udpipe.sh"

  - name: evaluate_homercy
    help: Evaluate homerCy models on the test sets, generate metrics report
    script:
      - "bash scripts/homercy/evaluate_homercy.sh"

  - name: evaluate_grecy
    help: Evaluate greCy models on test folds, generate metrics report
    script:
      - "bash scripts/grecy/evaluate_grecy.sh"

  - name: evaluate_trankit
    help: Evaluate Trankit models on test folds, generate metrics report
    script:
      - "bash scripts/trankit/evaluate_trankit.sh"